<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16404" started-at="2017-11-27T14:45:07Z" finished-at="2017-11-27T14:45:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16404" started-at="2017-11-27T14:45:07Z" finished-at="2017-11-27T14:45:23Z">
      <class name="com.automation.training.SignIn">
        <test-method status="PASS" signature="invokeBrowser()[pri:0, instance:com.automation.training.SignIn@1d057a39]" name="invokeBrowser" is-config="true" duration-ms="6219" started-at="2017-11-27T09:45:07Z" finished-at="2017-11-27T09:45:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invokeBrowser -->
        <test-method status="FAIL" signature="loginToJabong()[pri:0, instance:com.automation.training.SignIn@1d057a39]" name="loginToJabong" duration-ms="8008" started-at="2017-11-27T09:45:13Z" finished-at="2017-11-27T09:45:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Hey Cristian] but found [Jabong| Best Online Fashion & Lifestyle Shopping Site In India| Big Brands, Best Prices]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Hey Cristian] but found [Jabong| Best Online Fashion & Lifestyle Shopping Site In India| Big Brands, Best Prices]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.automation.training.SignIn.loginToJabong(SignIn.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToJabong -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.automation.training.SignIn@1d057a39]" name="closeBrowser" is-config="true" duration-ms="2171" started-at="2017-11-27T09:45:21Z" finished-at="2017-11-27T09:45:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.automation.training.SignIn -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
